name: Accessible Sortable List
author: mashalla
category: Widgets
tags: [widget, sortable, list, drag and drop, WAI ARIA]
demo: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
current: 1.0